### ISSUE TITLE
Overlay

### ISSUE THREAD

**Issue by prodrummer5** [fwumdesoft/Ants#6]
An overlay is urgently required in order for further testing of the game to be done.

**Comment by Jarbo52** [comment]
Working on it slowly but surely

**Comment by prodrummer5** [comment]
We will probably need to work on showing the Evo(Tech) tree now

**Comment by prodrummer5** [comment]
Before we do anything else with the overlay, the scaling bug with the overlay needs to be fixed since you cannot click the buttons unless you are at default window size.

**Comment by prodrummer5** [comment]
After about 10 minutes of pure rage, I have made the overlay stop scaling

**Comment by inser7Name** [comment]
The overlay now properly responds to scaling
